import colours from "./pages/data/colours.json";
const {
  green,
  purple,
  red,
  aqua,
  orange,
  yellow,
  gray,
  white,
  blue,
  black,
  pink,
} = colours.standard;

import { SpeedDuelDeck, StructureDeck } from "./types";

const speedDuelDecks: SpeedDuelDeck[] = [
  {
    year: 2022,
    type: "speed",
    code: "SGX1-ENS05",
    name: "Alexis - Cyber Blade Fusion",
    color: pink,
  },
  {
    year: 2023,
    type: "speed",
    code: "SGX3-ENS04",
    name: "Tania - Welcome to the Jungle",
    color: orange,
  },
  {
    year: 2019,
    type: "speed",
    code: "SS03-ENAS2",
    name: "Rex - Nightmare Sonic Blast!",
    color: red,
  },
  {
    year: 2022,
    type: "speed",
    code: "SGX1-ENS04",
    name: "Dr. Crowler - Ancient Fusion",
    color: blue,
  },
  {
    year: 2022,
    type: "speed",
    code: "SGX2-ENS03",
    name: "Syrus - The Roids are Alright",
    color: blue,
  },
  {
    year: 2022,
    type: "speed",
    code: "SGX1-ENS06",
    name: "Jesse - Crystal Transcendence",
    color: white,
  },
  {
    year: 2022,
    type: "speed",
    code: "SGX2-ENS04",
    name: "Paradox - Behold, Gate Guardian!",
    color: black,
  },
  {
    year: 2023,
    type: "speed",
    code: "SGX3-ENS08",
    name: "Adrian - Fog Warning",
    color: aqua,
  },
  {
    year: 2022,
    type: "speed",
    code: "SGX1-ENS16",
    name: "Axel - Volcanic Cannon",
    color: red,
  },
  {
    year: 2020,
    type: "speed",
    code: "DEM6-ENS01",
    name: "Yami Yugi - Power Up!",
    color: yellow,
  },
  {
    year: 2023,
    type: "speed",
    code: "SGX3-ENS05",
    name: "Titan - Archfiend's Conscription",
    color: red,
  },
  {
    year: 2023,
    type: "speed",
    code: "SGX3-ENS03",
    name: "Camula - Vampiric Aristocracy",
    color: purple,
  },
  {
    year: 2022,
    type: "speed",
    code: "SGX2-ENS01",
    name: "Jaden - HEROES UNITE - FUSION!!",
    color: orange,
  },
  {
    year: 2022,
    type: "speed",
    code: "SGX2-ENS02",
    name: "Bastion - Chemistry in Motion",
    color: aqua,
  },
  {
    year: 2023,
    type: "speed",
    code: "SGX3-ENS06",
    name: "Amnael - Professor of Alchemy",
    color: yellow,
  },
  {
    year: 2023,
    type: "speed",
    code: "SGX3-ENS09",
    name: "Supreme King - Dark Unity",
    color: yellow,
  },
  {
    year: 2023,
    type: "speed",
    code: "SS03-ENBS1",
    name: "Weevil - Hyper Metamorphosis",
    color: green,
  },
  {
    year: 2022,
    type: "speed",
    code: "SGX1-ENS07",
    name: "Zane - Forbidden Cyber Style Technique",
    color: blue,
  },
  {
    year: 2022,
    type: "speed",
    code: "SGX1-ENS09",
    name: "Jaden - The Right Hero for the Job",
    color: blue,
  },
  {
    year: 2023,
    type: "speed",
    code: "SGX3-ENS10",
    name: "Nightshroud - Dragon Force",
    color: blue,
  },
  {
    year: 2022,
    type: "speed",
    code: "SGX1-ENS11",
    name: "Chazz - Armed and Ready!",
    color: green,
  },
  {
    year: 2023,
    type: "speed",
    code: "SGX3-ENS07",
    name: "Kagemaru - Unlocking the Power",
    color: black,
  },
  {
    year: 2022,
    type: "speed",
    code: "SGX1-ENS10",
    name: "Aster - Looking into the Future",
    color: black,
  },
];

const structureDecks: StructureDeck[] = [
  {
    month: 0,
    year: 2005,
    type: "structure",
    code: "SD1",
    name: "Dragon's Roar",
    color: green,
  },
  {
    month: 0,
    year: 2005,
    type: "structure",
    code: "SD2",
    name: "Zombie Madness",
    color: purple,
  },
  {
    month: 4,
    year: 2005,
    type: "structure",
    code: "SD3",
    name: "Blaze of Destruction",
    color: red,
  },
  {
    month: 4,
    year: 2005,
    type: "structure",
    code: "SD4",
    name: "Fury from the Deep",
    color: aqua,
  },
  {
    month: 9,
    year: 2005,
    type: "structure",
    code: "SD5",
    name: "Warrior's Triumph",
    color: orange,
  },
  {
    month: 0,
    year: 2006,
    type: "structure",
    code: "SD6",
    name: "Spellcaster's Judgment",
    color: yellow,
  },
  {
    month: 4,
    year: 2006,
    type: "structure",
    code: "SD7",
    name: "Invincible Fortress",
    color: gray,
  },
  {
    month: 6,
    year: 2006,
    type: "structure",
    code: "SD8",
    name: "Lord of the Storm",
    color: white,
  },
  {
    month: 5,
    year: 2006,
    type: "structure",
    code: "SD09",
    name: "Dinosaur's Rage",
    color: red,
  },
  {
    month: 0,
    year: 2007,
    type: "structure",
    code: "SD10",
    name: "Machine Re-Volt",
    color: blue,
  },
  {
    month: 9,
    year: 2007,
    type: "structure",
    code: "SDRL",
    name: "Rise of the Dragon Lords",
    color: green,
  },
  {
    month: 3,
    year: 2008,
    type: "structure",
    code: "SDDE",
    name: "The Dark Emperor",
    color: black,
  },
  {
    month: 9,
    year: 2008,
    type: "structure",
    code: "SDZW",
    name: "Zombie World",
    color: purple,
  },
  {
    month: 2,
    year: 2009,
    type: "structure",
    code: "SDSC",
    name: "Spellcaster's Command",
    color: yellow,
  },
  {
    month: 9,
    year: 2009,
    type: "structure",
    code: "SDWS",
    name: "Warriors' Strike",
    color: orange,
  },
  {
    month: 1,
    year: 2010,
    type: "structure",
    code: "SDMM",
    name: "Machina Mayhem",
    color: blue,
  },
  {
    month: 9,
    year: 2010,
    type: "structure",
    code: "SDMA",
    name: "Marik",
    color: yellow,
  },
  {
    month: 2,
    year: 2011,
    type: "structure",
    code: "SDDL",
    name: "Dragunity Legion",
    color: green,
  },
  {
    month: 5,
    year: 2011,
    type: "structure",
    code: "SDLS",
    name: "Lost Sanctuary",
    color: white,
  },
  {
    month: 9,
    year: 2011,
    type: "structure",
    code: "SDGU",
    name: "Gates of the Underworld",
    color: black,
  },
  {
    month: 1,
    year: 2012,
    type: "structure",
    code: "SDDC",
    name: "Dragons Collide",
    color: white,
  },
  {
    month: 5,
    year: 2012,
    type: "structure",
    code: "SDWA",
    name: "Samurai Warlords",
    color: orange,
  },
  {
    month: 9,
    year: 2012,
    type: "structure",
    code: "SDRE",
    name: "Realm of the Sea Emperor",
    color: aqua,
  },
  {
    month: 1,
    year: 2013,
    type: "structure",
    code: "SDOK",
    name: "Onslaught of the Fire Kings",
    color: red,
  },
  {
    month: 8,
    year: 2013,
    type: "structure",
    code: "SDBE",
    name: "Saga of Blue-Eyes White Dragon",
    color: green,
  },
  {
    month: 1,
    year: 2014,
    type: "structure",
    code: "SDCR",
    name: "Cyber Dragon Revolution",
    color: blue,
  },
  {
    month: 5,
    year: 2014,
    type: "structure",
    code: "SDLI",
    name: "Realm of Light",
    color: white,
  },
  {
    month: 9,
    year: 2014,
    type: "structure",
    code: "SDGR",
    name: "Geargia Rampage",
    color: blue,
  },
  {
    month: 0,
    year: 2015,
    type: "structure",
    code: "SDHS",
    name: "HERO Strike",
    color: orange,
  },
  {
    month: 7,
    year: 2015,
    type: "structure",
    code: "SDSE",
    name: "Synchron Extreme",
    color: pink,
  },
  {
    month: 11,
    year: 2015,
    type: "structure",
    code: "SDMP",
    name: "Master of Pendulum",
    color: pink,
  },
  {
    month: 0,
    year: 2016,
    type: "structure",
    code: "SR01",
    name: "Emperor of Darkness",
    color: black,
  },
  {
    month: 6,
    year: 2016,
    type: "structure",
    code: "SR02",
    name: "Rise of the True Dragons",
    color: green,
  },
  {
    month: 9,
    year: 2016,
    type: "structure",
    code: "SDMY",
    name: "Yugi Muto",
    color: black,
  },
  {
    month: 9,
    year: 2016,
    type: "structure",
    code: "SDKS",
    name: "Seto Kaiba",
    color: yellow,
  },
  {
    month: 0,
    year: 2017,
    type: "structure",
    code: "SDPD",
    name: "Pendulum Domination",
    color: pink,
  },
  {
    month: 3,
    year: 2017,
    type: "structure",
    code: "SR03",
    name: "Machine Reactor",
    color: black,
  },
  {
    month: 3,
    year: 2017,
    type: "structure",
    code: "SR04",
    name: "Dinosmasher's Fury",
    color: red,
  },
  {
    month: 10,
    year: 2017,
    type: "structure",
    code: "SDCL",
    name: "Cyberse Link",
    color: pink,
  },
  {
    month: 0,
    year: 2018,
    type: "structure",
    code: "SR05",
    name: "Wave of Light",
    color: white,
  },
  {
    month: 3,
    year: 2018,
    type: "structure",
    code: "SR06",
    name: "Lair of Darkness",
    color: black,
  },
  {
    month: 7,
    year: 2018,
    type: "structure",
    code: "SDPL",
    name: "Powercode Link",
    color: pink,
  },
  {
    month: 10,
    year: 2018,
    type: "structure",
    code: "SR07",
    name: "Zombie Horde",
    color: purple,
  },
  {
    month: 1,
    year: 2019,
    type: "structure",
    code: "SDSB",
    name: "Soulburner",
    color: red,
  },
  {
    month: 3,
    year: 2019,
    type: "structure",
    code: "SR08",
    name: "Order of the Spellcasters",
    color: green,
  },
  {
    month: 7,
    year: 2019,
    type: "structure",
    code: "SDRR",
    name: "Rokket Revolt",
    color: green,
  },
  {
    month: 1,
    year: 2020,
    type: "structure",
    code: "SDSH",
    name: "Shaddoll Showdown",
    color: purple,
  },
  {
    month: 3,
    year: 2020,
    type: "structure",
    code: "SR10",
    name: "Mechanized Madness",
    color: blue,
  },
  {
    month: 6,
    year: 2020,
    type: "structure",
    code: "SDSA",
    name: "Sacred Beasts",
    color: black,
  },
  {
    month: 10,
    year: 2020,
    type: "structure",
    code: "SDCH",
    name: "Spirit Charmers",
    color: black,
  },
  {
    month: 1,
    year: 2021,
    type: "structure",
    code: "SDFC",
    name: "Freezing Chains",
    color: green,
  },
  {
    month: 9,
    year: 2021,
    type: "structure",
    code: "SDCS",
    name: "Cyber Strike",
    color: blue,
  },
  {
    month: 3,
    year: 2022,
    type: "structure",
    code: "SDAZ",
    name: "Albaz Strike",
    color: red,
  },
  {
    month: 8,
    year: 2022,
    type: "structure",
    code: "SDCB",
    name: "Legend of Crystal Beasts",
    color: white,
  },
  {
    month: 11,
    year: 2022,
    type: "structure",
    code: "SR13",
    name: "Dark World",
    color: black,
  },
  {
    month: 1,
    year: 2023,
    type: "structure",
    code: "SDBT",
    name: "Beware of Traptrix",
    color: pink,
  },
  {
    month: 8,
    year: 2023,
    type: "structure",
    code: "SDCK",
    name: "The Crimson King",
    color: red,
  },
];

export default [...structureDecks, ...speedDuelDecks];
