import colours from "./pages/data/colours.json";
const {
  green,
  purple,
  red,
  aqua,
  orange,
  yellow,
  gray,
  white,
  blue,
  black,
  pink,
} = colours.standard;

import { SpeedDuelDeck, StructureDeck } from "./types";

const speedDuelDecks: SpeedDuelDeck[] = [
  {
    type: "speed",
    code: "SGX1-ENS05",
    name: "Alexis - Cyber Blade Fusion",
    color: pink,
  },
  {
    type: "speed",
    code: "SGX3-ENS04",
    name: "Tania - Welcome to the Jungle",
    color: orange,
  },
  {
    type: "speed",
    code: "SS03-ENAS2",
    name: "Rex - Nightmare Sonic Blast!",
    color: red,
  },
  {
    type: "speed",
    code: "SGX1-ENS04",
    name: "Dr. Crowler - Ancient Fusion",
    color: blue,
  },
  {
    type: "speed",
    code: "SGX2-ENS03",
    name: "Syrus - The Roids are Alright",
    color: blue,
  },
  {
    type: "speed",
    code: "SGX1-ENS06",
    name: "Jesse - Crystal Transcendence",
    color: white,
  },
  {
    type: "speed",
    code: "SGX2-ENS04",
    name: "Paradox - Behold, Gate Guardian!",
    color: black,
  },
  {
    type: "speed",
    code: "SGX3-ENS08",
    name: "Adrian - Fog Warning",
    color: aqua,
  },
  {
    type: "speed",
    code: "SGX1-ENS16",
    name: "Axel - Volcanic Cannon",
    color: red,
  },
  {
    type: "speed",
    code: "DEM6-ENS01",
    name: "Yami Yugi - Power Up!",
    color: yellow,
  },
  {
    type: "speed",
    code: "SGX3-ENS05",
    name: "Titan - Archfiend's Conscription",
    color: red,
  },
  {
    type: "speed",
    code: "SGX3-ENS03",
    name: "Camula - Vampiric Aristocracy",
    color: purple,
  },
  {
    type: "speed",
    code: "SGX2-ENS01",
    name: "Jaden - HEROES UNITE - FUSION!!",
    color: orange,
  },
  {
    type: "speed",
    code: "SGX2-ENS02",
    name: "Bastion - Chemistry in Motion",
    color: aqua,
  },
  {
    type: "speed",
    code: "SGX3-ENS06",
    name: "Amnael - Professor of Alchemy",
    color: yellow,
  },
  {
    type: "speed",
    code: "SGX3-ENS09",
    name: "Supreme King - Dark Unity",
    color: yellow,
  },
  {
    type: "speed",
    code: "SS03-ENBS1",
    name: "Weevil - Hyper Metamorphosis",
    color: green,
  },
  {
    type: "speed",
    code: "SGX1-ENS07",
    name: "Zane - Forbidden Cyber Style Technique",
    color: blue,
  },
  {
    type: "speed",
    code: "SGX1-ENS09",
    name: "Jaden - The Right Hero for the Job",
    color: blue,
  },
  {
    type: "speed",
    code: "SGX3-ENS10",
    name: "Nightshroud - Dragon Force",
    color: blue,
  },
  {
    type: "speed",
    code: "SGX1-ENS11",
    name: "Chazz - Armed and Ready!",
    color: green,
  },
  {
    type: "speed",
    code: "SGX3-ENS07",
    name: "Kagemaru - Unlocking the Power",
    color: black,
  },
  {
    type: "speed",
    code: "SGX1-ENS10",
    name: "Aster - Looking into the Future",
    color: black,
  },
];

const structureDecks: StructureDeck[] = [
  { type: "structure", code: "SD1", name: "Dragon's Roar", color: green },
  { type: "structure", code: "SD2", name: "Zombie Madness", color: purple },
  { type: "structure", code: "SD3", name: "Blaze of Destruction", color: red },
  { type: "structure", code: "SD4", name: "Fury from the Deep", color: aqua },
  { type: "structure", code: "SD5", name: "Warrior's Triumph", color: orange },
  {
    type: "structure",
    code: "SD6",
    name: "Spellcaster's Judgment",
    color: yellow,
  },
  { type: "structure", code: "SD7", name: "Invincible Fortress", color: gray },
  { type: "structure", code: "SD8", name: "Lord of the Storm", color: white },
  { type: "structure", code: "SD09", name: "Dinosaur's Rage", color: red },
  { type: "structure", code: "SD10", name: "Machine Re-Volt", color: blue },
  {
    type: "structure",
    code: "SDRL",
    name: "Rise of the Dragon Lords",
    color: green,
  },
  { type: "structure", code: "SDDE", name: "The Dark Emperor", color: black },
  { type: "structure", code: "SDZW", name: "Zombie World", color: purple },
  {
    type: "structure",
    code: "SDSC",
    name: "Spellcaster's Command",
    color: yellow,
  },
  { type: "structure", code: "SDWS", name: "Warriors' Strike", color: orange },
  { type: "structure", code: "SDMM", name: "Machina Mayhem", color: blue },
  { type: "structure", code: "SDMA", name: "Marik", color: yellow },
  { type: "structure", code: "SDDL", name: "Dragunity Legion", color: green },
  { type: "structure", code: "SDLS", name: "Lost Sanctuary", color: white },
  {
    type: "structure",
    code: "SDGU",
    name: "Gates of the Underworld",
    color: black,
  },
  { type: "structure", code: "SDDC", name: "Dragons Collide", color: white },
  { type: "structure", code: "SDWA", name: "Samurai Warlords", color: orange },
  {
    type: "structure",
    code: "SDRE",
    name: "Realm of the Sea Emperor",
    color: aqua,
  },
  {
    type: "structure",
    code: "SDOK",
    name: "Onslaught of the Fire Kings",
    color: red,
  },
  {
    type: "structure",
    code: "SDBE",
    name: "Saga of Blue-Eyes White Dragon",
    color: green,
  },
  {
    type: "structure",
    code: "SDCR",
    name: "Cyber Dragon Revolution",
    color: blue,
  },
  { type: "structure", code: "SDLI", name: "Realm of Light", color: white },
  { type: "structure", code: "SDGR", name: "Geargia Rampage", color: blue },
  { type: "structure", code: "SDHS", name: "HERO Strike", color: orange },
  { type: "structure", code: "SDSE", name: "Synchron Extreme", color: pink },
  { type: "structure", code: "SDMP", name: "Master of Pendulum", color: pink },
  {
    type: "structure",
    code: "SR01",
    name: "Emperor of Darkness",
    color: black,
  },
  {
    type: "structure",
    code: "SR02",
    name: "Rise of the True Dragons",
    color: green,
  },
  { type: "structure", code: "SDMY", name: "Yugi Muto", color: black },
  { type: "structure", code: "SDKS", name: "Seto Kaiba", color: yellow },
  { type: "structure", code: "SDPD", name: "Pendulum Domination", color: pink },
  { type: "structure", code: "SR03", name: "Machine Reactor", color: black },
  { type: "structure", code: "SR04", name: "Dinosmasher's Fury", color: red },
  { type: "structure", code: "SDCL", name: "Cyberse Link", color: pink },
  { type: "structure", code: "SR05", name: "Wave of Light", color: white },
  { type: "structure", code: "SR06", name: "Lair of Darkness", color: black },
  { type: "structure", code: "SDPL", name: "Powercode Link", color: pink },
  { type: "structure", code: "SR07", name: "Zombie Horde", color: purple },
  { type: "structure", code: "SDSB", name: "Soulburner", color: red },
  {
    type: "structure",
    code: "SR08",
    name: "Order of the Spellcasters",
    color: green,
  },
  { type: "structure", code: "SDRR", name: "Rokket Revolt", color: green },
  { type: "structure", code: "SDSH", name: "Shaddoll Showdown", color: purple },
  { type: "structure", code: "SR10", name: "Mechanized Madness", color: blue },
  { type: "structure", code: "SDSA", name: "Sacred Beasts", color: black },
  { type: "structure", code: "SDCH", name: "Spirit Charmers", color: black },
  { type: "structure", code: "SDFC", name: "Freezing Chains", color: green },
  { type: "structure", code: "SDCS", name: "Cyber Strike", color: blue },
  { type: "structure", code: "SDAZ", name: "Albaz Strike", color: red },
  {
    type: "structure",
    code: "SDCB",
    name: "Legend of Crystal Beasts",
    color: white,
  },
  { type: "structure", code: "SDBT", name: "Beware of Traptrix", color: pink },
  { type: "structure", code: "SR13", name: "Dark World", color: black },
  { type: "structure", code: "SDCK", name: "The Crimson King", color: red },
];

export default [...structureDecks, ...speedDuelDecks];
