const decks = [
  { code: "SD1", name: "Dragon's Roar" },
  { code: "SD2", name: "Zombie Madness" },
  { code: "SD3", name: "Blaze of Destruction" },
  { code: "SD4", name: "Fury from the Deep" },
  { code: "SD5", name: "Warrior's Triumph" },
  { code: "SD6", name: "Spellcaster's Judgment" },
  { code: "SD7", name: "Invincible Fortress" },
  { code: "SD8", name: "Lord of the Storm" },
  { code: "SD09", name: "Dinosaur's Rage" },
  { code: "SD10", name: "Machine Re-Volt" },
  { code: "SDRL", name: "Rise of the Dragon Lords" },
  { code: "SDDE", name: "The Dark Emperor" },
  { code: "SDZW", name: "Zombie World" },
  { code: "SDSC", name: "Spellcaster's Command" },
  { code: "SDWS", name: "Warriors' Strike" },
  { code: "SDMM", name: "Machina Mayhem" },
  { code: "SDMA", name: "Marik" },
  { code: "SDDL", name: "Dragunity Legion" },
  { code: "SDLS", name: "Lost Sanctuary" },
  { code: "SDGU", name: "Gates of the Underworld" },
  { code: "SDDC", name: "Dragons Collide" },
  { code: "SDWA", name: "Samurai Warlords" },
  { code: "SDRE", name: "Realm of the Sea Emperor" },
  { code: "SDOK", name: "Onslaught of the Fire Kings" },
  { code: "SDBE", name: "Saga of Blue-Eyes White Dragon" },
  { code: "SDCR", name: "Cyber Dragon Revolution" },
  { code: "SDLI", name: "Realm of Light" },
  { code: "SDGR", name: "Geargia Rampage" },
  { code: "SDHS", name: "HERO Strike" },
  { code: "SDSE", name: "Synchron Extrme" },
  { code: "SDMP", name: "Master of Pendulum" },
  { code: "SR01", name: "Emperor of Darkness" },
  { code: "SR02", name: "Rise of the True Dragons" },
  { code: "SDMY", name: "Yugi Muto" },
  { code: "SDKS", name: "Seto Kaiba" },
  { code: "SDPD", name: "Pendulum Domination" },
  { code: "SR03", name: "Machine Reactor" },
  { code: "SR04", name: "Dinosmasher's Fury" },
  { code: "SDCL", name: "Cyberse Link" },
  { code: "SR05", name: "Wave of Light" },
  { code: "SR06", name: "Lair of Darkness" },
  { code: "SDPL", name: "Powercode Link" },
  { code: "SR07", name: "Zombie Horde" },
  { code: "SDSB", name: "Soulburner" },
  { code: "SR08", name: "Order of the Spellcasters" },
  { code: "SDRR", name: "Rokket Revolt" },
  { code: "SDSH", name: "Shaddoll Showdown" },
  { code: "SR10", name: "Mechanized Madness" },
  { code: "SDSA", name: "Sacred Beasts" },
];

export default decks;
